"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Semver__factory = exports.NodeRegistry__factory = exports.ISemver__factory = exports.INodeRegistry__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var INodeRegistry__factory_1 = require("./INodeRegistry__factory");
Object.defineProperty(exports, "INodeRegistry__factory", { enumerable: true, get: function () { return INodeRegistry__factory_1.INodeRegistry__factory; } });
var ISemver__factory_1 = require("./ISemver__factory");
Object.defineProperty(exports, "ISemver__factory", { enumerable: true, get: function () { return ISemver__factory_1.ISemver__factory; } });
var NodeRegistry__factory_1 = require("./NodeRegistry__factory");
Object.defineProperty(exports, "NodeRegistry__factory", { enumerable: true, get: function () { return NodeRegistry__factory_1.NodeRegistry__factory; } });
var Semver__factory_1 = require("./Semver__factory");
Object.defineProperty(exports, "Semver__factory", { enumerable: true, get: function () { return Semver__factory_1.Semver__factory; } });
//# sourceMappingURL=index.js.map